// lib/championData.js
//
// Loads the champion ID -> name map generated by scripts/fetch-champion-data.js
// and exposes a simple lookup function.

const fs = require('fs');
const path = require('path');

let cache = null;

function load() {
    if (cache) return cache;

    const filePath = path.join(__dirname, '..', 'assets', 'champions.json');
    if (!fs.existsSync(filePath)) {
        throw new Error(
            'assets/champions.json not found. Run `node scripts/fetch-champion-data.js` first.'
        );
    }

    const raw = fs.readFileSync(filePath, 'utf-8');
    cache = JSON.parse(raw)
    return cache;
}

// championId comes from the LCU as a number; Data Dragon keys are strings.
// championId 0 means "no champion selected yet".
function championName(championId) {
    if (!championId || championId === 0) return null;
    const { idToName } = load();
    return idToName[String(championId)] || `Unknown (${championId})`;
}

module.exports = { championName };