// lib/championData.js
//
// Loads the champion ID -> name map generated by scripts/fetch-champion-data.js
// and exposes a simple lookup function.

const fs = require('fs');
const path = require('path');

let cache = null;

function load() {
    if (cache) return cache;

    const filePath = path.join(__dirname, '..', 'assets', 'champions.json');
    if (!fs.existsSync(filePath)) {
        throw new Error(
            'assets/champions.json not found. Run `node scripts/fetch-champion-data.js` first.'
        );
    }

    const raw = fs.readFileSync(filePath, 'utf-8');
    cache = JSON.parse(raw)
    return cache;
}

// championId comes from the LCU as a number; Data Dragon keys are strings.
// championId 0 means "no champion selected yet".
function championName(championId) {
    if (!championId || championId === 0) return null;
    const { idToName } = load();
    return idToName[String(championId)] || `Unknown (${championId})`;
}

// Builds a Data Dragon square-icon URL for a champion, given either its
// display name ("Wukong") or an already-id-style name ("MonkeyKing" - what
// match/population data is keyed by). Looks up the real Data Dragon id via
// nameToId first; falls back to stripping punctuation/spaces from the input
// if there's no match (works for the ~90% of champs where id === name
// minus punctuation, e.g. "Miss Fortune" -> "MissFortune"; will 404 for the
// handful of true renames like Wukong until nameToId is populated).
// Returns null if champions.json hasn't been fetched at all.
function championIconUrl(name) {
    if (!name) return null;
    let version, nameToId;
    try {
        ({ version, nameToId } = load());
    } catch {
        return null;
    }
    const id = (nameToId && nameToId[name]) || name.replace(/[^A-Za-z0-9]/g, '');
    if (!id) return null;
    return `https://ddragon.leagueoflegends.com/cdn/${version}/img/champion/${id}.png`;
}

module.exports = { championName, championIconUrl };