// lib/populationStats.js
//
// Looks up rank-specific population win rate data generated by
// scripts/fetch-population-data.js, optionally sliced by patch or by a
// rolling day window.
//
// SCOPE NOTE: patch/date filtering only applies to the main tier baseline
// (stats.tiers). Matchup and synergy data (stats.matchups / stats.synergies)
// stay all-time aggregates - see the comment above
// getPopulationMatchupStats for why.

const DAY_MS = 24 * 60 * 60 * 1000;

function sumEntries(entries) {
    let games = 0, wins = 0;
    for (const e of entries) {
        games += e.games;
        wins += e.wins;
    }
    return { games, wins };
}

// filter shapes (all optional - undefined means "all-time"):
//   { type: 'all' }
//   { type: 'patch', patch: '15.18' }
//   { type: 'days', days: 30, now?: <epoch ms, defaults to Date.now()> }
function resolveEntry(entry, filter) {
    if (!entry) return { games: 0, wins: 0 };

    if (!filter || filter.type === 'all') {
        return { games: entry.games, wins: entry.wins };
    }

    if (filter.type === 'patch') {
        const bucket = entry.byPatch && entry.byPatch[filter.patch];
        return bucket ? { games: bucket.games, wins: bucket.wins } : { games: 0, wins: 0 };
    }

    if (filter.type === 'days') {
        const now = filter.now || Date.now();
        const cutoff = now - filter.days * DAY_MS;
        const byDate = entry.byDate || {};
        const inWindow = Object.entries(byDate)
            .filter(([dateStr]) => new Date(`${dateStr}T00:00:00Z`).getTime() >= cutoff)
            .map(([, v]) => v);
        return sumEntries(inWindow);
    }

    // Unrecognized filter shape - fail open to all-time rather than
    // silently showing zero data.
    return { games: entry.games, wins: entry.wins };
}

function toStat(resolved) {
    if (!resolved || resolved.games === 0) return null;
    const winRate = Math.round((resolved.wins / resolved.games) * 1000) / 10;
    return { games: resolved.games, wins: resolved.wins, winRate };
}

function getPopulationStats(populationData, tier, championName, filter) {
    const entry = populationData?.tiers?.[tier]?.[championName];
    return toStat(resolveEntry(entry, filter));
}

// Matchup/synergy sample sizes are already much smaller than the baseline
// win-rate data (one row per enemy/ally champion seen, not per game), so
// slicing them further by patch would mostly produce n=0 noise rather than
// a useful signal. Left as all-time aggregates. If wanted later,
// replicate the byPatch/byDate treatment from recordResult() in
// scripts/fetch-population-data.js onto recordMatchup/recordSynergy.
function getPopulationMatchupStats(populationData, tier, championName, enemyChampionName) {
    const entry = populationData?.matchups?.[tier]?.[championName]?.[enemyChampionName];
    if (!entry || entry.games === 0) return null;
    const winRate = Math.round((entry.wins / entry.games) * 1000) / 10;
    return { games: entry.games, wins: entry.wins, winRate };
}

function getPopulationSynergyStats(populationData, tier, championName, allyChampionName) {
    const entry = populationData?.synergies?.[tier]?.[championName]?.[allyChampionName];
    if (!entry || entry.games === 0) return null;
    const winRate = Math.round((entry.wins / entry.games) * 1000) / 10;
    return { games: entry.games, wins: entry.wins, winRate };
}

// Every patch string seen anywhere in the tiers data, newest first - for
// the settings page's patch <select>. Sorts numerically on major/minor
// (string sort alone breaks on "15.9" vs "15.18").
function getAvailablePatches(populationData) {
    const patches = new Set();
    for (const champs of Object.values(populationData?.tiers || {})) {
        for (const entry of Object.values(champs)) {
            for (const patch of Object.keys(entry.byPatch || {})) {
                patches.add(patch);
            }
        }
    }
    return [...patches].sort((a, b) => {
        const [aMaj, aMin] = a.split('.').map(Number);
        const [bMaj, bMin] = b.split('.').map(Number);
        return bMaj - aMaj || bMin - aMin;
    });
}

module.exports = {
    getPopulationStats,
    getPopulationMatchupStats,
    getPopulationSynergyStats,
    getAvailablePatches
};