// lib/populationStats.js
//
// Looks up rank-specific population win rate data generated by
// scripts/fetch-population-data.js.

function getPopulationStats(populationData, tier, championName) {
    const champs = populationData?.tiers?.[tier];
    if (!champs) return null;

    const entry = champs[championName];
    if (!entry || entry.games === 0) return null;

    const winRate = Math.round((entry.wins / entry.games) * 1000) / 10;
    return { games: entry.games, wins: entry.wins, winRate };
}

function getPopulationMatchupStats(populationData, tier, championName, enemyChampionName) {
    const entry = populationData?.matchups?.[tier]?.[championName]?.[enemyChampionName];
    if (!entry || entry.games === 0) return null;

    const winRate = Math.round((entry.wins / entry.games) * 1000) / 10;
    return { games: entry.games, wins: entry.wins, winRate };
}

function getPopulationSynergyStats(populationData, tier, championName, allyChampionName) {
    const entry = populationData?.synergies?.[tier]?.[championName]?.[allyChampionName];
    if (!entry || entry.games === 0) return null;

    const winRate = Math.round((entry.wins / entry.games) * 1000) / 10;
    return { games: entry.games, wins: entry.wins, winRate };
}

module.exports = { getPopulationStats, getPopulationMatchupStats, getPopulationSynergyStats };